### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by ashrafalzyoud** [eXolnet/redmine_wbs#59]
in your description 
`In the directory #{REDMINE_ROOT}/plugins/redmine_pulls, compile the assets:
`
where i found redmine pulls???
because no output come
![image](https://github.com/eXolnet/redmine_wbs/assets/50211455/dd202683-cb49-495a-8321-11896dbd6ac2)

**Comment by xel1045** [comment]
It's a typo in the docs. The right folder should be: `{REDMINE_ROOT}/plugins/redmine_wbs`
